name: 🔓 create-key-vault
run-name: (${{ inputs.key-vault }}) create
on:
  workflow_dispatch:
    inputs:
      azurerm-env:
        description: Azure RM Environment
        type: choice
        options:
          - azure
      resource-group:
        description: Resource group to deploy in.
        required: true
        default: gh-copilot
      key-vault:
        description: Key Vault name.
        required: true
        default: sp-key-vault-909

permissions:
  id-token: write
  contents: read

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: ${{ inputs.azurerm-env }}
    steps:
      - uses: actions/checkout@v2

      - name: load env
        run: cat ./.github/env/azurerm.env >> $GITHUB_ENV

      - name: az login
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: create key vault
        run: |
          az keyvault create --name ${{ inputs.key-vault }} --resource-group ${{ inputs.resource-group }} --location westeurope

